### PR TITLE
Various changes for usability

### LINKED ISSUE #6: Keyboard keys < and > do not work
Pressing either `<` or `>` results in `>` being pressed on the remote.

This breaks tasks like writing HTML in the session.

May need to re-write the python keyboard input handler to use the Xlib directly rather than relying on pynput to do the right thing.
[Example](https://stackoverflow.com/a/18062387)

### PR DESCRIPTION
**Pull request by ehfd**
- Remove tkinter dependency, not needed after all
- Allow empty username for basic authentication if there is no $USER
- Fix docs and base example image behavior
- Ensure that libvpx is explicitly installed and supported
- Change default from nvh264enc to x264enc so the project will start up by default without a NVIDIA GPU
- Remove CPU thread restriction with vpx and x264, encoder will automatically determine number of threads (it was better, at least for me)
- Fix #6.

### CODE REVIEW

**Comment by ehfd** [comment]
image

#6 fixed with minimal side effects.

**Comment by ehfd** [comment]
Closes #6.

**Comment by ehfd** [comment]
Note that we would want GStreamer 1.21.1 before a release when this is merged.

**Comment by ehfd** [comment]
Ready for review @danisla

**Comment by ehfd** [comment]
Fixes a lot of #40 but we'll put the rest in another PR.

**Comment by ehfd** [comment]
@danisla This can be merged. If I have something else I will raise another issue.

**Comment by danisla** [comment]
LGTM

**Pull request merged**
