### PR TITLE
Logging webrtc statistics on host received over datachannel

### PR DESCRIPTION
**Pull request by PMohanJ**
This is a DRAFT: Do not merge it yet.

The reports are being sent over datachannel and being dumped to a CSV file at `/tmp/stats.csv` location.
Due to duel webrtc connection the audio stats aren't included yet as the file size keeps increasing rapidly even with just video webrtc api stats.

#139

### CODE REVIEW

**Comment by ehfd** [comment]
File size is probably expected.

**Comment by ehfd** [comment]
Closes #139

**Comment by PMohanJ** [comment]
So for audio stats, should they be in a separate csv file?

**Comment by ehfd** [comment]
That would be desirable.

**Comment by PMohanJ** [comment]
The changes include logging of webrtc statistics of both audio and video reports. Also the logging of stats is per session based, meaning that for every new session new stats files are generated. This is done to maintain the structure of csv file as different browsers provide statistics in different order.

**Review by ehfd — APPROVED** [review]
I am happy with the changes.

**Pull request merged**
